---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3gw-config
  namespace: {{ .Release.Namespace }}
data:
  RGW_BACKEND_STORE: "sfs"
  DEBUG_RGW: "1"
{{- if .Values.ui.enabled }}
  RGW_SERVICE_URL: 'api'
{{- end }}
