---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-dpl'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "s3gw.selectorLabels" . | indent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
{{ include "s3gw.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image:
            '{{ .Values.imageRegistry }}/{{ .Values.imageName }}:{{ .Values.imageTag }}'
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - "--rgw-backend-store"
            - $(RGW_BACKEND_STORE)
            - "--debug-rgw"
            - $(DEBUG_RGW)
          ports:
            - containerPort: 7480
              name: s3
          envFrom:
            - configMapRef:
                name: s3gw-config
            - secretRef:
                name: s3gw-secret
          volumeMounts:
            - name: s3gw-lh-store
              mountPath: /data
      volumes:
        - name: s3gw-lh-store
          persistentVolumeClaim:
{{- if eq .Values.storageType "pvc" }}
            claimName: {{ .Values.storage }}
{{- else if eq .Values.storageType "local" }}
            claimName: '{{ .Release.Name }}-local-pvc'
{{- else }}
            claimName: s3gw-pvc
{{- end }}
