{{ if .Values.enableIngress }}
---
# TLS Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Chart.Name }}-tls'
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares:
      '{{ .Release.Namespace }}-cors-header@kubernetescrd,{{ .Release.Namespace }}-strip-api-prefix@kubernetescrd'
spec:
  tls:
    - hosts:
        - '{{ .Values.hostname }}'
      secretName: '{{ .Chart.Name }}-ingress-secret'
  rules:
    - host: '{{ .Values.hostname }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{ .Chart.Name }}-svc'
                port:
                  number: 80
---
# No TLS Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Chart.Name }}-no-tls'
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares:
      '{{ .Release.Namespace }}-cors-header@kubernetescrd,{{ .Release.Namespace }}-strip-api-prefix@kubernetescrd'
spec:
  rules:
    - host: 'no-tls-{{ .Values.hostname }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{ .Chart.Name }}-svc'
                port:
                  number: 80
{{- if .Values.ui.enabled }}
---
# UI TLS Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Chart.Name }}-ui-tls'
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares:
      '{{ .Release.Namespace }}-cors-header@kubernetescrd'
spec:
  tls:
    - hosts:
        - 'ui-{{ .Values.hostname }}'
      secretName: '{{ .Chart.Name }}-ingress-secret'
  rules:
    - host: 'ui-{{ .Values.hostname }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{ .Chart.Name }}-ui-svc'
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: '{{ .Chart.Name }}-svc'
                port:
                  number: 80
---
# UI No TLS Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Chart.Name }}-ui-no-tls'
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares:
      '{{ .Release.Namespace }}-cors-header@kubernetescrd'
spec:
  rules:
    - host: 'no-tls-ui-{{ .Values.hostname }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{ .Chart.Name }}-ui-svc'
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: '{{ .Chart.Name }}-svc'
                port:
                  number: 80
---
# Middleware for Traefik
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /api
    forceSlash: false
{{- end }}
---
# Middleware for Traefik
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-header
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    accessControlAllowMethods:
      - "DELETE"
      - "GET"
      - "HEAD"
      - "POST"
      - "PUT"
    accessControlAllowOriginList:
      - "*"
    accessControlAllowHeaders:
      - "*"
{{- end }}
