---
apiVersion: v1
kind: Secret
metadata:
  name: 'certificates-{{ .Values.hostname }}'
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.tls.crt }}
  tls.key: |
    {{ .Values.tls.key }}
{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: 'certificates-{{ .Values.ui.hostname }}'
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.ui.tls.crt }}
  tls.key: |
    {{ .Values.ui.tls.key }}
{{- end }}
