---
apiVersion: v1
kind: Secret
metadata:
  name: 'certificates-{{ .Values.serviceName }}.{{ .Values.publicDomain }}'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.tls.crt }}
  tls.key: |
    {{ .Values.tls.key }}
{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: 'certificates-{{ .Values.ui.serviceName }}.{{ .Values.ui.publicDomain }}'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.ui.tls.crt }}
  tls.key: |
    {{ .Values.ui.tls.key }}
{{- end }}
