---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Chart.Name }}-ingress-secret'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{ .Values.tls.crt }}
  tls.key: |
    {{ .Values.tls.key }}
