{{- if eq .Values.storageType "longhorn" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-single
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3gw-pvc
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
spec:
  storageClassName: longhorn-single
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
{{- end }}
