---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Chart.Name }}-secret'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
type: Opaque
stringData:
  RGW_DEFAULT_USER_ID: {{ .Values.userID | quote }}
  RGW_DEFAULT_USER_DISPLAY_NAME: {{ .Values.userDisplayName | quote }}
  RGW_DEFAULT_USER_EMAIL: {{ .Values.userEmail | quote }}
  RGW_DEFAULT_USER_CAPS: {{ .Values.userCapabilities | quote }}
  RGW_DEFAULT_USER_SYSTEM: "1"
  RGW_DEFAULT_USER_ASSUMED_ROLE_ARN: ""
  RGW_DEFAULT_USER_ACCESS_KEY: {{ .Values.accessKey | quote }}
  RGW_DEFAULT_USER_SECRET_KEY: {{ .Values.secretKey | quote }}
