---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-svc'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
spec:
  selector:
    app.aquarist-labs.io/name: {{ .Chart.Name }}
  ports:
    - name: s3
      protocol: TCP
      port: 80
      targetPort: s3
