---
name: Lint and Test Charts

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/lint-and-test.yaml'
      - 'charts/**/*'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.6.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch \
            ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: |
          ct lint --target-branch \
            ${{ github.event.repository.default_branch }} \
            --check-version-increment=false

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: |
          ct install --target-branch \
            ${{ github.event.repository.default_branch }} \
            --chart-repos \
            ingress-traefik=https://helm.traefik.io/traefik \
            --helm-extra-set-args="--set=storageType=local,storage=/tmp/local-storage,enableIngress=false" \
            --helm-extra-args="--timeout=500s" \
            --debug
