---
name: Lint, Test and Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.6.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch \
            ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: |
          ct lint --target-branch \
            ${{ github.event.repository.default_branch }} \
            --validate-maintainers=false

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          export CONFIG="storageClass.name=local"
          export CONFIG="$CONFIG,storageClass.create=true"
          export CONFIG="$CONFIG,storageClass.local=true"
          export CONFIG="$CONFIG,storageClass.localPath=/tmp/local-storage"
          export CONFIG="$CONFIG,ingress.enabled=false"
          export CONFIG="$CONFIG,ui.enabled=false"

          ct install --target-branch \
            ${{ github.event.repository.default_branch }} \
            --helm-extra-set-args="--set=${CONFIG}" \
            --helm-extra-args="--timeout=500s" \
            --debug

  # If a push to main happens (i.e. when merging PRs), release the chart.
  release:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - lint-and-test

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"


      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
