---
name: Lint, Test and Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.10.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.6.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch \
            ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: |
          ct lint --target-branch \
            ${{ github.event.repository.default_branch }} \
            --validate-maintainers=false

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          export CONFIG="storageClass.name=local"
          export CONFIG="$CONFIG,storageClass.create=true"
          export CONFIG="$CONFIG,storageClass.local=true"
          export CONFIG="$CONFIG,storageClass.localPath=/tmp/local-storage"
          export CONFIG="$CONFIG,ingress.enabled=false"
          export CONFIG="$CONFIG,ui.enabled=false"

          ct install --target-branch \
            ${{ github.event.repository.default_branch }} \
            --helm-extra-set-args="--set=${CONFIG}" \
            --helm-extra-args="--timeout=500s" \
            --debug

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - lint-and-test

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          docker run --rm \
            -v ${GITHUB_WORKSPACE}:/chart \
            -e CR_TOKEN=${CR_TOKEN} \
            quay.io/helmpack/chart-releaser \
            -- package s3gw \
                  --package-path .cr-release-packages

          docker run --rm \
            -v ${GITHUB_WORKSPACE}:/chart \
            -e CR_TOKEN=${CR_TOKEN} \
            quay.io/helmpack/chart-releaser \
            -- upload \
                  -o "${{ env.GITHUB_REPOSITORY_OWNER }}" \
                  -r s3gw-charts \
                  -c "$(git rev-parse HEAD)"

          docker run --rm \
            -v ${GITHUB_WORKSPACE}:/chart \
            -e CR_TOKEN=${CR_TOKEN} \
            quay.io/helmpack/chart-releaser \
            -- index \
                  -o "${{ env.GITHUB_REPOSITORY_OWNER }}" \
                  -r s3gw-charts \
                  --push
